title: DOLLARTACOS
email: admin@dollarta.co
description: Handmade artisan keycaps.
baseurl: ""
url: "https://www.dollarta.co"

markdown: kramdown

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
